controller:
  hostNetwork: true
  hostPort:
    enabled: true
  ingressClassResource:
    default: true
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: "10G"
    nginx.ingress.kubernetes.io/client-body-buffer-size: "10G"
  config:
    proxy-body-size: "10G"
defaultBackend:
  enabled: false
  port: 80
