apiVersion: v1
kind: ConfigMap
metadata:
  name: csi-ceph-conf-override
  namespace: rook-ceph # namespace:operator
data:
  ceph.conf: |
    [global]
    fsid = rook-ceph
    mon host = 192.168.5.200
