apiVersion: ceph.rook.io/v1
kind: CephFilesystem
metadata:
  name: nas
  namespace: rook-ceph
spec:
  metadataPool:
    failureDomain: osd
    replicated:
      size: 2
  dataPools:
    - name: replicated
      failureDomain: osd
      replicated:
        size: 2
  preserveFilesystemOnDelete: true
  metadataServer:
    activeCount: 1
    activeStandby: false
