apiVersion: v1
kind: ConfigMap
metadata:
  name: clash-etc
  namespace: clash
data:
  config.yaml: |+
    mixed-port: 7890
    allow-lan: true
    bind-address: '*'
    mode: rule
    log-level: info
    external-controller: '0.0.0.0:9090'
    dns:
        enable: true
        ipv6: false
        default-nameserver: [223.5.5.5, 119.29.29.29]
        enhanced-mode: redir-host
        fake-ip-range: 198.18.0.1/16
        use-hosts: true
        nameserver: ['https://doh.pub/dns-query', 'https://dns.alidns.com/dns-query']
        fallback: ['https://doh.dns.sb/dns-query', 'https://dns.cloudflare.com/dns-query', 'https://dns.twnic.tw/dns-query', 'tls://8.8.4.4:853']
        fallback-filter: { geoip: true, ipcidr: [240.0.0.0/4, 0.0.0.0/32] }
    proxies:
        - { name: 'us', type: ss, server: 153.101.64.221, port: 17006, cipher: aes-256-gcm, password: 5be81841-7162-1160-29bd-329e584305bf, udp: true }
    proxy-groups:
        - { name: 极光加速, type: select, proxies: [ 'us' ] }
    rules:
        - 'DOMAIN,jgjs2-connect.com,DIRECT'
        - 'DOMAIN-SUFFIX,services.googleapis.cn,极光加速'
        - 'DOMAIN-SUFFIX,xn--ngstr-lra8j.com,极光加速'
        - 'DOMAIN,safebrowsing.urlsec.qq.com,DIRECT'
        - 'DOMAIN,safebrowsing.googleapis.com,DIRECT'
        - 'DOMAIN,developer.apple.com,极光加速'
        - 'DOMAIN-SUFFIX,digicert.com,极光加速'
        - 'IP-CIDR,91.108.4.0/22,极光加速,no-resolve'
        - 'IP-CIDR,91.108.8.0/21,极光加速,no-resolve'
        - 'IP-CIDR,91.108.16.0/22,极光加速,no-resolve'
        - 'IP-CIDR,91.108.56.0/22,极光加速,no-resolve'
        - 'IP-CIDR,149.154.160.0/20,极光加速,no-resolve'
        - 'IP-CIDR6,2001:67c:4e8::/48,极光加速,no-resolve'
        - 'IP-CIDR6,2001:b28:f23d::/48,极光加速,no-resolve'
        - 'IP-CIDR6,2001:b28:f23f::/48,极光加速,no-resolve'
        - 'IP-CIDR,120.232.181.162/32,极光加速,no-resolve'
        - 'IP-CIDR,120.241.147.226/32,极光加速,no-resolve'
        - 'IP-CIDR,120.253.253.226/32,极光加速,no-resolve'
        - 'IP-CIDR,120.253.255.162/32,极光加速,no-resolve'
        - 'IP-CIDR,120.253.255.34/32,极光加速,no-resolve'
        - 'IP-CIDR,120.253.255.98/32,极光加速,no-resolve'
        - 'IP-CIDR,180.163.150.162/32,极光加速,no-resolve'
        - 'IP-CIDR,180.163.150.34/32,极光加速,no-resolve'
        - 'IP-CIDR,180.163.151.162/32,极光加速,no-resolve'
        - 'IP-CIDR,180.163.151.34/32,极光加速,no-resolve'
        - 'IP-CIDR,203.208.39.0/24,极光加速,no-resolve'
        - 'IP-CIDR,203.208.40.0/24,极光加速,no-resolve'
        - 'IP-CIDR,203.208.41.0/24,极光加速,no-resolve'
        - 'IP-CIDR,203.208.43.0/24,极光加速,no-resolve'
        - 'IP-CIDR,203.208.50.0/24,极光加速,no-resolve'
        - 'IP-CIDR,220.181.174.162/32,极光加速,no-resolve'
        - 'IP-CIDR,220.181.174.226/32,极光加速,no-resolve'
        - 'IP-CIDR,220.181.174.34/32,极光加速,no-resolve'
        - 'DOMAIN,injections.adguard.org,DIRECT'
        - 'DOMAIN,local.adguard.org,DIRECT'
        - 'DOMAIN-SUFFIX,local,DIRECT'
        - 'IP-CIDR,127.0.0.0/8,DIRECT'
        - 'IP-CIDR,172.16.0.0/12,DIRECT'
        - 'IP-CIDR,192.168.0.0/16,DIRECT'
        - 'IP-CIDR,10.0.0.0/8,DIRECT'
        - 'IP-CIDR,17.0.0.0/8,DIRECT'
        - 'IP-CIDR,100.64.0.0/10,DIRECT'
        - 'IP-CIDR,224.0.0.0/4,DIRECT'
        - 'IP-CIDR6,fe80::/10,DIRECT'
        - 'DOMAIN-SUFFIX,cn,DIRECT'
        - 'DOMAIN-KEYWORD,-cn,DIRECT'
        - 'GEOIP,CN,DIRECT'
        - 'MATCH,极光加速'
