apiVersion: apps/v1
kind: Deployment
metadata:
  name: clash-all
  namespace: clash
spec:
  selector:
    matchLabels:
      application: clash
      component: clash-all
  template:
    metadata:
      labels:
        application: clash
        component: clash-all
    spec:
      containers:
        - image: shoppon/clash:latest
          name: clash
          # command: ["/bin/bash", "-c", "--"]
          # args: ["while true; do sleep 30; done;"]
          command:
            - "clash"
            - "-d"
            - "/etc/clash/"
          imagePullPolicy: IfNotPresent
          livenessProbe:
            exec:
              command:
                - /usr/bin/curl
                - -x
                - http://127.0.0.1:7890
                - https://www.google.com.hk
            initialDelaySeconds: 10
            periodSeconds: 30
            timeoutSeconds: 5
          resources:
            limits:
              cpu: 500m
              memory: 1Gi
            requests:
              cpu: 500m
              memory: 1Gi
          volumeMounts:
            - name: clash-etc
              mountPath: /etc/clash/config.yaml
              subPath: all.yaml
              readOnly: true
      volumes:
        - name: clash-etc
          configMap:
            name: clash-etc
