apiVersion: v1
kind: ConfigMap
metadata:
  name: srs-config
  labels:
    app: srs
data:
  srs.conf: |
    listen              1935;
    max_connections     1000;
    srs_log_tank        file;
    srs_log_file        ./objs/srs.log;

    http_api {
        enabled         on;
        listen          1985;
        crossdomain     on;
    }

    http_server {
        enabled         on;
        listen          8080;
        dir             ./objs/nginx/html;
    }

    rtc_server {
        enabled on;
        listen 8000;
        candidate $CANDIDATE;
    }

    vhost __defaultVhost__ {
        hls {
            enabled         on;
            hls_path        ./objs/nginx/html;
            hls_fragment    10;
            hls_window      60;
        }
        http_remux {
            enabled     on;
            mount       [vhost]/[app]/[stream].flv;
            hstrs       on;
        }
        rtc {
            enabled     on;
            rtmp_to_rtc on;
            rtc_to_rtmp on;
        }
        dvr {
            enabled      off;
            dvr_path     ./objs/nginx/html/[app]/[stream]/[2006]/[01]/[02]/[stream]-[15]:[04]:[05].flv;
            dvr_plan     session;
        }
        gb28181 {
            enabled on;
            listen 5060;
            host $CANDIDATE;
            auto_create_channel on;
            rtp_port_min 58200;
            rtp_port_max 58300;
        }
    }

    stats {
        network         0;
        disk            sda vda xvda xvdb;
    }
