apiVersion: v1
kind: ConfigMap
metadata:
  name: ceph-etc
  namespace: ceph
data:
  ceph.conf: |+
    [global]
    fsid = ff3db042-5bbe-42a9-91ec-d28b730edbaa
    mon initial members = t630
    mon host = 192.168.5.200
    public network = 192.168.5.0/24
    cluster network = 192.168.5.0/24
    auth cluster required = cephx
    auth service required = cephx
    auth client required = cephx
    # auth cluster required = none
    # auth service required = none
    # auth client required = none
    osd journal size = 1024
    osd pool default size = 2
    osd pool default min size = 1
    osd pool default pg num = 512
    osd pool default pgp num = 512
    osd crush chooseleaf type = 1
    mgr module path = /root/mgr
    mgr initial modules = restful
    [osd]
    debug_osd = 1/5
    [mds.t630]
    host = t630
  ceph.mon.keyring: |+
    [mon.]
        key = AQD+IH9jHIAUOBAAo2BuHdJog9kq2G5U3QrRrg==
        caps mon = "allow *"
    [client.admin]
        key = AQDgK39jzfktFBAAbaduKhYk3nnAUhJQ1Amz7g==
        caps mds = "allow *"
        caps mgr = "allow *"
        caps mon = "allow *"
        caps osd = "allow *"
    [client.bootstrap-osd]
        key = AQBMLH9jRJNbDhAAtB0n9G1fp+w9ryr7+2YbAw==
        caps mgr = "allow r"
        caps mon = "profile bootstrap-osd"
  ceph.client.admin.keyring: |+
    [client.admin]
        key = AQDgK39jzfktFBAAbaduKhYk3nnAUhJQ1Amz7g==
        caps mds = "allow *"
        caps mgr = "allow *"
        caps mon = "allow *"
        caps osd = "allow *"
  ceph.client.bootstrap-osd.keyring: |+
    [client.bootstrap-osd]
        key = AQBMLH9jRJNbDhAAtB0n9G1fp+w9ryr7+2YbAw==
        caps mgr = "allow r"
        caps mon = "profile bootstrap-osd"
