apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: ceph-mds
  namespace: ceph
spec:
  selector:
    matchLabels:
      application: ceph
      component: mds
  template:
    metadata:
      labels:
        application: ceph
        component: mds
    spec:
      hostNetwork: true
      serviceAccount: default
      hostPID: true
      containers:
        - name: ceph-mds
          image: shoppon/ceph:16.2.10-ubuntu-20.04
          imagePullPolicy: Always
          securityContext:
            privileged: true
          # command: ["/bin/bash", "-c", "--"]
          # args: ["while true; do sleep 30; done;"]
          command: ["ceph-mds"]
          args:
            - "-f"
            - "--cluster"
            - "ceph"
            - "--id"
            - "t630"
            - "-d"
            - "-m"
            - "192.168.5.200:6789"
          volumeMounts:
            - name: ceph-etc
              mountPath: /etc/ceph
            - name: ceph-data
              mountPath: /var/lib/ceph/
            - name: ceph-log
              mountPath: /var/log/ceph
            - name: ceph-dev
              mountPath: /dev
            - name: ceph-run
              mountPath: /var/run/ceph
            - name: ceph-bin
              mountPath: /usr/ceph
      volumes:
        - name: ceph-etc
          configMap:
            name: ceph-etc
        - name: ceph-bin
          configMap:
            name: ceph-bin
        - name: ceph-data
          hostPath:
            path: /var/lib/ceph/
            type: DirectoryOrCreate
        - name: ceph-log
          hostPath:
            path: /var/log/ceph/
            type: DirectoryOrCreate
        - name: ceph-dev
          hostPath:
            path: /dev/
            type: Directory
        - name: ceph-run
          hostPath:
            path: /var/run/ceph
            type: DirectoryOrCreate
