apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: ceph-mon
  namespace: ceph
spec:
  selector:
    matchLabels:
      application: ceph
      component: mon
  template:
    metadata:
      labels:
        application: ceph
        component: mon
    spec:
      hostNetwork: true
      serviceAccount: default
      hostPID: true
      initContainers:
        - name: monmap
          image: shoppon/ceph:16.2.10-ubuntu-20.04
          imagePullPolicy: Always
          command: ["/bin/bash"]
          args:
            - -c
            - >-
              test -f /var/lib/ceph/monmap || monmaptool --create --add $(HOSTNAME) $(IPADDR) --fsid $(FSID) /var/lib/ceph/monmap
          env:
            - name: HOSTNAME
              value: t630
            - name: IPADDR
              value: 192.168.5.200
            - name: FSID
              value: ff3db042-5bbe-42a9-91ec-d28b730edbaa
          volumeMounts:
            - name: ceph-etc
              mountPath: /etc/ceph
            - name: ceph-data
              mountPath: /var/lib/ceph
        - name: mkfs
          image: shoppon/ceph:16.2.10-ubuntu-20.04
          imagePullPolicy: Always
          command: ["/bin/bash"]
          args:
            - -c
            - >-
              test -f /var/lib/ceph/mon/ceph-$(HOSTNAME) || ceph-mon --mkfs -i $(HOSTNAME) --monmap /var/lib/ceph/monmap --keyring /etc/ceph/ceph.mon.keyring
          env:
            - name: HOSTNAME
              value: t630
          volumeMounts:
            - name: ceph-etc
              mountPath: /etc/ceph
            - name: ceph-data
              mountPath: /var/lib/ceph
      containers:
        - name: ceph-mon
          image: shoppon/ceph:16.2.10-ubuntu-20.04
          imagePullPolicy: IfNotPresent
          # command: ["/bin/bash", "-c", "--"]
          # args: ["while true; do sleep 30; done;"]
          command:
            [
              "ceph-mon",
              "-d",
              "-i",
              "$(HOSTNAME)",
              "--monmap",
              "/var/lib/ceph/monmap",
              "--keyring",
              "/etc/ceph/ceph.mon.keyring",
            ]
          env:
            - name: HOSTNAME
              value: t630
          volumeMounts:
            - name: ceph-etc
              mountPath: /etc/ceph
            - name: ceph-data
              mountPath: /var/lib/ceph/
            - name: ceph-log
              mountPath: /var/log/ceph
      volumes:
        - name: ceph-etc
          configMap:
            name: ceph-etc
        - name: ceph-data
          hostPath:
            path: /var/lib/ceph/
            type: DirectoryOrCreate
        - name: ceph-log
          hostPath:
            path: /var/log/ceph/
            type: DirectoryOrCreate
