apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: ceph-mgr
  namespace: ceph
spec:
  selector:
    matchLabels:
      application: ceph
      component: mgr
  template:
    metadata:
      labels:
        application: ceph
        component: mgr
    spec:
      hostNetwork: true
      serviceAccount: default
      hostPID: true
      initContainers:
        - name: prepare
          image: shoppon/ceph:16.2.10-ubuntu-20.04
          imagePullPolicy: Always
          securityContext:
            privileged: true
          # command: ["/bin/bash", "-c", "--"]
          # args: ["while true; do sleep 30; done;"]
          command: ["/bin/bash", "/usr/ceph/ceph-mgr-prepare.sh"]
          volumeMounts:
            - name: ceph-etc
              mountPath: /etc/ceph
            - name: ceph-bin
              mountPath: /usr/ceph
            - name: ceph-data
              mountPath: /var/lib/ceph
            - name: ceph-dev
              mountPath: /dev
            - name: ceph-run
              mountPath: /var/run/ceph
      containers:
        - name: ceph-mgr
          image: shoppon/ceph:16.2.10-ubuntu-20.04
          imagePullPolicy: Always
          securityContext:
            privileged: true
          # command: ["/bin/bash", "-c", "--"]
          # args: ["while true; do sleep 30; done;"]
          command: ["ceph-mgr", "-i", "x", "-d"]
          volumeMounts:
            - name: ceph-etc
              mountPath: /etc/ceph
            - name: ceph-data
              mountPath: /var/lib/ceph/
            - name: ceph-log
              mountPath: /var/log/ceph
            - name: ceph-dev
              mountPath: /dev
            - name: ceph-run
              mountPath: /var/run/ceph
            - name: ceph-bin
              mountPath: /usr/ceph
      volumes:
        - name: ceph-etc
          configMap:
            name: ceph-etc
        - name: ceph-bin
          configMap:
            name: ceph-bin
        - name: ceph-data
          hostPath:
            path: /var/lib/ceph/
            type: DirectoryOrCreate
        - name: ceph-log
          hostPath:
            path: /var/log/ceph/
            type: DirectoryOrCreate
        - name: ceph-dev
          hostPath:
            path: /dev/
            type: Directory
        - name: ceph-run
          hostPath:
            path: /var/run/ceph
            type: DirectoryOrCreate
