apiVersion: v1
kind: ConfigMap
metadata:
  name: keystone-etc
  namespace: keystone
data:
  keystone.conf: |+
    [DEFAULT]
    max_domain_tree_depth = 2
    transport_url = rabbit://rabbitmq:rabbitmq13579@rabbitmq.rabbitmq.svc.cluster.local:5672/openstack
    [auth]
    methods = external,password,token,oauth1,application_credential,saml2
    [cache]
    backend = oslo_cache.memcache_pool
    enabled = true
    memcache_servers = memcached.memcached.svc.cluster.local:11211
    [credential]
    key_repository = /etc/keystone/credential-keys/
    [database]
    connection = mysql+pymysql://root:mysql13579@mysql.mysql.svc.cluster.local:3306/keystone
    max_overflow = -1
    max_retries = -1
    [domain_quotas]
    domain_quotas_enabled = true
    quota_backup_gigabytes = -1
    quota_backups = -1
    quota_cores = -1
    quota_floatingip = -1
    quota_gigabytes = -1
    quota_instances = -1
    quota_loadbalancer = -1
    quota_network = -1
    quota_port = -1
    quota_ram = -1
    quota_router = -1
    quota_security_group = -1
    quota_security_group_rule = -1
    quota_snapshots = -1
    quota_subnet = -1
    quota_volumes = -1
    [identity]
    domain_configurations_from_database = true
    domain_specific_drivers_enabled = true
    [keystone_authtoken]
    auth_url = http://keystone-api.openstack.svc.cluster.local:80/v3
    domain_name = Default
    password = keystone
    project_domain_name = Default
    project_name = service
    user_domain_name = Default
    username = keystone
    [token]
    driver = memcache_pool
    expiration = 21600
    provider = fernet
