apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox
  namespace: default
spec:
  selector:
    matchLabels:
      application: busybox
      component: busybox
  template:
    metadata:
      labels:
        application: busybox
        component: busybox
    spec:
      containers:
        - image: shoppon/busybox:latest
          name: busybox
          command: ["/bin/bash", "-c", "--"]
          args: ["while true; do sleep 30; done;"]
          imagePullPolicy: IfNotPresent
          env:
            - name: OS_USERNAME
              value: admin
            - name: OS_PASSWORD
              value: password
            - name: OS_AUTH_URL
              value: http://keystone-api.openstack.svc.cluster.local:5000/v3
            - name: OS_PROJECT_NAME
              value: admin
            - name: OS_USER_DOMAIN_NAME
              value: Default
            - name: OS_PROJECT_DOMAIN_NAME
              value: Default
            - name: OS_IDENTITY_API_VERSION
              value: "3"
            - name: OS_REGION_NAME
              value: RegionOne
            - name: OS_ENDPOINT_TYPE
              value: adminURL
            - name: OS_INTERFACE
              value: adminURL
            - name: OS_DEFAULT_DOMAIN
              value: Default
            - name: PYTHONIOENCODING
              value: UTF-8
          resources:
            limits:
              cpu: 1000m
              memory: 1Gi
            requests:
              cpu: 1000m
              memory: 1Gi
          volumeMounts:
            - name: kubecfg
              mountPath: /root/.kube/config
              readOnly: true
            - name: kubectl
              mountPath: /usr/local/bin/kubectl
              readOnly: true
            - name: ceph-etc
              mountPath: /etc/ceph/
              readOnly: true
      volumes:
        - name: kubectl
          hostPath:
            path: /usr/bin/kubectl
            type: File
        - name: kubecfg
          hostPath:
            path: /root/.kube/config
            type: File
        - name: ceph-etc
          configMap:
            name: ceph-etc
