apiVersion: v1
kind: PersistentVolume
metadata:
  name: ceph-rbd
  labels:
    type: local
spec:
  storageClassName: ceph-csi-rbd
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/ceph-rbd"
