apiVersion: v1
kind: Secret
metadata:
  name: csi-rbd-secret
  namespace: ceph-csi-rbd
type: Opaque
stringData:
  ceph.client.admin.keyring: |+
    [client.admin]
        key = AQDgK39jzfktFBAAbaduKhYk3nnAUhJQ1Amz7g==
        caps mds = "allow *"
        caps mgr = "allow *"
        caps mon = "allow *"
        caps osd = "allow *"
