apiVersion: v1
kind: Pod
metadata:
  name: cm-test
  namespace: default
  labels:
    application: cm-test
    component: cm-test
spec:
  volumes:
    - name: alcubierre
      configMap:
        name: alcubierre
  containers:
    - name: cm-test
      image: shoppon/busybox:latest
      command: ["/bin/bash", "-c", "sleep 10d"]
      resources:
        limits:
          cpu: 100m
          memory: 128Mi
      volumeMounts:
        - mountPath: /tmp/alcubierre.pyc
          name: alcubierre
          subPath: node_group.pyc