apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-old
  namespace: minio-old
spec:
  storageClassName: csi-rbd-sc
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Gi
