apiVersion: v1
kind: Pod
metadata:
  name: mongo
  namespace: mongo
  labels:
    application: mongo
    component: mongo
spec:
  volumes:
    - name: mongo
      persistentVolumeClaim:
        claimName: mongo
  containers:
    - name: mongo
      image: mongo:latest
      resources:
        limits:
          cpu: 2000m
          memory: 2Gi
        requests:
          cpu: 2000m
          memory: 2Gi
      volumeMounts:
        - mountPath: "/data/db"
          name: mongo
      env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: root
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: mongo
