apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo
  namespace: mongo
spec:
  storageClassName: hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
