apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo
  namespace: mongo
spec:
  storageClassName: rook-ceph-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 60Gi
