apiVersion: v1
kind: Service
metadata:
  name: mongo
  namespace: mongo
spec:
  type: NodePort
  selector:
    application: mongo
    component: mongo
  ports:
    - port: 27017
      targetPort: 27017
      nodePort: 32717