apiVersion: v1
kind: Service
metadata:
  name: mongo
  namespace: mongo
spec:
  type: ClusterIP
  ports:
    - name: mongo
      port: 27017
      targetPort: 27017
      protocol: TCP
  selector:
    application: mongo
    component: mongo
